language: node_js

node_js:
    - "0.10"
    - "0.12"

branches:
    only:
        - master

# Update npm to the latest version
before_install: npm update -g npm

# travis runs 'npm install' by default, as the 'install' step

before_script: npm run dist;
# travis runs 'npm test' by default, as the 'script' step

# PLACEHOLDER FOR COVERAGE REPORTS ON GITHUB, IF WE WANT THEM.
# ALSO NEED TO ADD .coveralls.yml, IF WE WANT TO USE IT ON THE PRIVATE
# REPO.

after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - npm run deploy-ghpages

notifications:
    email:
        falcor@netflix.com
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/73bb75f713e1f5b6e860
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
